export { default as Navbar } from './Navbar.vue'
export { default as Sidebar } from './Sidebar/base-sidebar.vue'
export { default as Settings } from './Settings/base-settings.vue'
export { default as AppMain } from './AppMain.vue'
export { default as TagsView } from './TagsView/base-tags-view.vue'
